AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10  #change time as per your requirements
    MemorySize: 128
    Tracing: Active
  Api:
    TracingEnabled: true

Resources:
  MyExpressFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: app/         #change to your renamed folder
      Handler: app.handler  #change from lambdaHandler to handler
      Runtime: nodejs14.x
      Architectures:
      - x86_64
      Events:
        MyExpress:    #change all occurances to your specified name like MyExpress
          Type: Api   # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}    #change to express route as /{proxy+}
            Method: any        #change to any

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Join:
        - ''
        - - ApplicationInsights-SAM-
          - Ref: AWS::StackName
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Fn::Join:
        - ''
        - - ApplicationInsights-SAM-
          - Ref: AWS::StackName
      AutoConfigurationEnabled: 'true'
    DependsOn: ApplicationResourceGroup
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MyExpressApi:
    Description: API Gateway endpoint URL for Prod stage for MyExpress function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/" #remove hello
  MyExpressFunction:
    Description: MyExpress Lambda Function ARN    #change all occurances to your specified name like MyExpress
    Value: !GetAtt MyExpressFunction.Arn
  MyExpressFunctionIamRole:
    Description: Implicit IAM Role created for MyExpress function
    Value: !GetAtt MyExpressFunctionRole.Arn
